package com.example.ui.screens

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.School
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.local.entity.QuestionEntity
import com.example.ui.theme.CyanBright
import com.example.ui.theme.CyanPrimary
import com.example.ui.theme.EmeraldSuccess
import com.example.ui.theme.RoseError
import com.example.ui.theme.Slate700
import com.example.ui.theme.Slate800
import com.example.ui.theme.Slate850
import com.example.ui.theme.Slate900
import com.example.ui.theme.Slate950
import com.example.viewmodel.FocusinViewModel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AiQuizGeneratorScreen(
    chapterId: String,
    viewModel: FocusinViewModel,
    onNavigateBack: () -> Unit
) {
    val chapter by viewModel.getChapterFlow(chapterId).collectAsState(initial = null)
    val coroutineScope = rememberCoroutineScope()

    var isGenerating by remember { mutableStateOf(false) }
    var quizGenerated by remember { mutableStateOf(false) }
    var selectedDifficulty by remember { mutableStateOf("BALANCED") } // "EASY", "BALANCED", "HARD"
    var questionCount by remember { mutableIntStateOf(5) } // 5, 10

    // Simulated Generated Quiz Questions (grounded in syllabus & topics)
    val generatedQuestions = remember {
        mutableListOf(
            QuestionEntity(
                id = "ai_q_01",
                examId = "NEET",
                subjectId = chapter?.subjectId ?: "PHYSICS",
                chapterId = chapterId,
                topicName = "Kirchhoff's Voltage Law",
                questionText = "In a closed loop containing two resistors R1 = 4 Ω, R2 = 6 Ω and two opposing ideal batteries of 12 V and 4 V, what is the net potential drop across resistor R2?",
                optionA = "4.8 V",
                optionB = "3.2 V",
                optionC = "8.0 V",
                optionD = "6.0 V",
                correctOption = "A",
                explanation = "Net EMF in the circuit is 12 V - 4 V = 8 V. Total series resistance is 4 Ω + 6 Ω = 10 Ω. Current I = 8 / 10 = 0.8 A. Potential drop across R2 = I × R2 = 0.8 A × 6 Ω = 4.8 V.",
                difficulty = "MEDIUM"
            ),
            QuestionEntity(
                id = "ai_q_02",
                examId = "NEET",
                subjectId = chapter?.subjectId ?: "PHYSICS",
                chapterId = chapterId,
                topicName = "Internal Resistance & Terminal Voltage",
                questionText = "A cell provides a current of 0.5 A through an external resistor of 2 Ω, and 0.25 A through a resistor of 5 Ω. What is the internal resistance of the cell?",
                optionA = "1.0 Ω",
                optionB = "0.5 Ω",
                optionC = "2.0 Ω",
                optionD = "1.5 Ω",
                correctOption = "A",
                explanation = "EMF E = I(R + r). Thus E = 0.5(2 + r) and E = 0.25(5 + r). Equating both: 1 + 0.5r = 1.25 + 0.25r ==> 0.25r = 0.25 ==> r = 1.0 Ω.",
                difficulty = "MEDIUM"
            ),
            QuestionEntity(
                id = "ai_q_03",
                examId = "NEET",
                subjectId = chapter?.subjectId ?: "PHYSICS",
                chapterId = chapterId,
                topicName = "Heating Effect of Current",
                questionText = "If current through a fixed resistor is increased by 100%, what is the percentage increase in power dissipated across the resistor?",
                optionA = "100%",
                optionB = "200%",
                optionC = "300%",
                optionD = "400%",
                correctOption = "C",
                explanation = "Power P = I²R. When current doubles (I' = 2I), new power P' = (2I)²R = 4(I²R) = 4P. Percentage increase = ((4P - P)/P) × 100 = 300%.",
                difficulty = "EASY"
            ),
            QuestionEntity(
                id = "ai_q_04",
                examId = "NEET",
                subjectId = chapter?.subjectId ?: "PHYSICS",
                chapterId = chapterId,
                topicName = "Metre Bridge Sensitivity",
                questionText = "A Metre Bridge operates with the highest accuracy and sensitivity when the null balance point is obtained:",
                optionA = "Near 10 cm",
                optionB = "Near 50 cm (the center)",
                optionC = "Near 90 cm",
                optionD = "At either end of the wire",
                correctOption = "B",
                explanation = "A Wheatstone / Metre bridge has maximum sensitivity when all four resistance arms are nearly equal, which occurs when the balance point is close to the midpoint (50 cm).",
                difficulty = "EASY"
            ),
            QuestionEntity(
                id = "ai_q_05",
                examId = "NEET",
                subjectId = chapter?.subjectId ?: "PHYSICS",
                chapterId = chapterId,
                topicName = "Temperature Coefficient",
                questionText = "Which of the following materials possesses a negative temperature coefficient of resistance (resistance drops with increasing temperature)?",
                optionA = "Copper",
                optionB = "Nichrome",
                optionC = "Silicon (Semiconductor)",
                optionD = "Silver",
                correctOption = "C",
                explanation = "In intrinsic semiconductors like Silicon and Germanium, increasing temperature breaks covalent bonds, exponentially freeing charge carriers, leading to a negative temperature coefficient of resistance.",
                difficulty = "EASY"
            )
        )
    }

    // Active quiz taking states
    var currentQuizIndex by remember { mutableIntStateOf(0) }
    var selectedQuizOption by remember { mutableStateOf<String?>(null) }
    var hasAnsweredCurrent by remember { mutableStateOf(false) }
    var correctQuizScore by remember { mutableIntStateOf(0) }
    var quizFinished by remember { mutableStateOf(false) }

    Scaffold(
        containerColor = Slate950,
        topBar = {
            TopAppBar(
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Slate950,
                    titleContentColor = Color.White
                ),
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back", tint = Color.White)
                    }
                },
                title = {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(Icons.Default.AutoAwesome, contentDescription = null, tint = CyanPrimary)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = "AI Custom Quiz",
                            fontSize = 18.sp,
                            fontWeight = FontWeight.Bold,
                            color = Color.White
                        )
                    }
                }
            )
        }
    ) { innerPadding ->
        if (!quizGenerated) {
            // Configuration view
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding)
                    .padding(horizontal = 16.dp),
                contentPadding = PaddingValues(top = 12.dp, bottom = 40.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                item {
                    Card(
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = Slate900),
                        border = BorderStroke(1.dp, Slate800),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(modifier = Modifier.padding(18.dp)) {
                            Text(
                                text = "ADAPTIVE QUIZ GENERATOR",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                letterSpacing = 1.sp,
                                color = CyanPrimary
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Text(
                                text = chapter?.name ?: "Target Chapter",
                                fontSize = 18.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White
                            )
                            Spacer(modifier = Modifier.height(6.dp))
                            Text(
                                text = "Generates NEET-pattern multi-choice questions targeting high-yield concepts and past exam traps.",
                                fontSize = 12.sp,
                                color = Color(0xFF94A3B8),
                                lineHeight = 16.sp
                            )
                        }
                    }
                }

                // Question Count Selector
                item {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text(
                            text = "QUESTION COUNT",
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            letterSpacing = 1.sp,
                            color = Color(0xFF64748B)
                        )
                        Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                            listOf(5 to "5 Questions (Quick)", 10 to "10 Questions (Standard)").forEach { (cnt, label) ->
                                val isSel = questionCount == cnt
                                Surface(
                                    color = if (isSel) Slate800 else Slate900,
                                    shape = RoundedCornerShape(10.dp),
                                    border = BorderStroke(1.dp, if (isSel) CyanPrimary else Slate800),
                                    modifier = Modifier
                                        .weight(1f)
                                        .clickable { questionCount = cnt }
                                ) {
                                    Text(
                                        text = label,
                                        fontSize = 12.sp,
                                        fontWeight = if (isSel) FontWeight.Bold else FontWeight.Normal,
                                        color = if (isSel) CyanPrimary else Color(0xFF94A3B8),
                                        modifier = Modifier.padding(12.dp)
                                    )
                                }
                            }
                        }
                    }
                }

                // Difficulty Mode Selector
                item {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text(
                            text = "DIFFICULTY RIGOR",
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            letterSpacing = 1.sp,
                            color = Color(0xFF64748B)
                        )
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            listOf("EASY" to "Foundation", "BALANCED" to "NEET Standard", "HARD" to "Challenger").forEach { (diffKey, label) ->
                                val isSel = selectedDifficulty == diffKey
                                Surface(
                                    color = if (isSel) Slate800 else Slate900,
                                    shape = RoundedCornerShape(10.dp),
                                    border = BorderStroke(1.dp, if (isSel) CyanPrimary else Slate800),
                                    modifier = Modifier
                                        .weight(1f)
                                        .clickable { selectedDifficulty = diffKey }
                                ) {
                                    Text(
                                        text = label,
                                        fontSize = 11.sp,
                                        fontWeight = if (isSel) FontWeight.Bold else FontWeight.Normal,
                                        color = if (isSel) CyanPrimary else Color(0xFF94A3B8),
                                        modifier = Modifier.padding(vertical = 10.dp, horizontal = 8.dp)
                                    )
                                }
                            }
                        }
                    }
                }

                // Generate Button
                item {
                    Button(
                        onClick = {
                            isGenerating = true
                            coroutineScope.launch {
                                delay(1200L) // Fast, smooth generation delay
                                isGenerating = false
                                quizGenerated = true
                            }
                        },
                        enabled = !isGenerating,
                        colors = ButtonDefaults.buttonColors(containerColor = CyanPrimary),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(50.dp)
                            .testTag("start_ai_quiz_button")
                    ) {
                        if (isGenerating) {
                            CircularProgressIndicator(color = Slate950, modifier = Modifier.size(18.dp))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Assembling Quiz...", color = Slate950, fontWeight = FontWeight.Bold)
                        } else {
                            Icon(Icons.Default.AutoAwesome, contentDescription = null, tint = Slate950, modifier = Modifier.size(18.dp))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Generate Quiz Now", color = Slate950, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                        }
                    }
                }
            }
        } else if (!quizFinished) {
            // Live Quiz Screen
            val q = generatedQuestions[currentQuizIndex]

            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding)
                    .padding(horizontal = 16.dp),
                contentPadding = PaddingValues(top = 8.dp, bottom = 40.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                item {
                    LinearProgressIndicator(
                        progress = { (currentQuizIndex + 1).toFloat() / generatedQuestions.size },
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(6.dp)
                            .clip(CircleShape),
                        color = CyanPrimary,
                        trackColor = Slate800
                    )
                }

                item {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = "QUESTION ${currentQuizIndex + 1} OF ${generatedQuestions.size}",
                            fontSize = 11.sp,
                            fontWeight = FontWeight.Bold,
                            color = CyanPrimary
                        )
                        Text(
                            text = q.topicName,
                            fontSize = 11.sp,
                            color = Color(0xFF94A3B8)
                        )
                    }
                }

                item {
                    Card(
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = Slate900),
                        border = BorderStroke(1.dp, Slate800),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(modifier = Modifier.padding(18.dp)) {
                            Text(
                                text = q.questionText,
                                fontSize = 15.sp,
                                fontWeight = FontWeight.Medium,
                                color = Color.White,
                                lineHeight = 22.sp
                            )
                        }
                    }
                }

                // Options
                item {
                    Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                        listOf("A" to q.optionA, "B" to q.optionB, "C" to q.optionC, "D" to q.optionD).forEach { (optKey, optText) ->
                            val isSel = selectedQuizOption == optKey
                            val isCorrect = optKey == q.correctOption

                            val bg = when {
                                hasAnsweredCurrent && isCorrect -> EmeraldSuccess.copy(alpha = 0.15f)
                                hasAnsweredCurrent && isSel && !isCorrect -> RoseError.copy(alpha = 0.15f)
                                isSel -> CyanPrimary.copy(alpha = 0.15f)
                                else -> Slate900
                            }

                            val border = when {
                                hasAnsweredCurrent && isCorrect -> EmeraldSuccess
                                hasAnsweredCurrent && isSel && !isCorrect -> RoseError
                                isSel -> CyanPrimary
                                else -> Slate800
                            }

                            Card(
                                shape = RoundedCornerShape(12.dp),
                                colors = CardDefaults.cardColors(containerColor = bg),
                                border = BorderStroke(1.dp, border),
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clickable(enabled = !hasAnsweredCurrent) {
                                        selectedQuizOption = optKey
                                    }
                            ) {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .padding(14.dp),
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Box(
                                        modifier = Modifier
                                            .size(28.dp)
                                            .clip(CircleShape)
                                            .background(if (isSel) CyanPrimary else Slate800),
                                        contentAlignment = Alignment.Center
                                    ) {
                                        Text(
                                            text = optKey,
                                            fontSize = 12.sp,
                                            fontWeight = FontWeight.Bold,
                                            color = if (isSel) Slate950 else Color.White
                                        )
                                    }
                                    Spacer(modifier = Modifier.width(12.dp))
                                    Text(text = optText, fontSize = 14.sp, color = Color.White, modifier = Modifier.weight(1f))
                                }
                            }
                        }
                    }
                }

                // Action button
                item {
                    if (!hasAnsweredCurrent) {
                        Button(
                            onClick = {
                                if (selectedQuizOption != null) {
                                    hasAnsweredCurrent = true
                                    if (selectedQuizOption == q.correctOption) {
                                        correctQuizScore++
                                    }
                                }
                            },
                            enabled = selectedQuizOption != null,
                            colors = ButtonDefaults.buttonColors(containerColor = CyanPrimary),
                            shape = RoundedCornerShape(12.dp),
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(48.dp)
                        ) {
                            Text("Confirm Answer", color = Slate950, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                        }
                    } else {
                        Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                            Card(
                                shape = RoundedCornerShape(12.dp),
                                colors = CardDefaults.cardColors(containerColor = Slate900),
                                border = BorderStroke(1.dp, Slate800),
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Column(modifier = Modifier.padding(14.dp)) {
                                    Text(
                                        text = if (selectedQuizOption == q.correctOption) "Correct Solution" else "Correction: Correct is (${q.correctOption})",
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 13.sp,
                                        color = if (selectedQuizOption == q.correctOption) EmeraldSuccess else RoseError
                                    )
                                    Spacer(modifier = Modifier.height(4.dp))
                                    Text(text = q.explanation, fontSize = 12.sp, color = Color(0xFFCBD5E1))
                                }
                            }

                            Button(
                                onClick = {
                                    if (currentQuizIndex < generatedQuestions.size - 1) {
                                        currentQuizIndex++
                                        selectedQuizOption = null
                                        hasAnsweredCurrent = false
                                    } else {
                                        quizFinished = true
                                        // Save to database
                                        viewModel.recordQuizAttempt(
                                            subjectId = chapter?.subjectId ?: "PHYSICS",
                                            chapterId = chapterId,
                                            chapterName = chapter?.name ?: "Current Electricity",
                                            totalQuestions = generatedQuestions.size,
                                            correctAnswers = correctQuizScore,
                                            timeTakenSeconds = 180,
                                            strongTopics = listOf("Heating Effect", "Temperature Coefficient"),
                                            weakTopics = listOf("Kirchhoff's Voltage Law")
                                        )
                                    }
                                },
                                colors = ButtonDefaults.buttonColors(containerColor = CyanPrimary),
                                shape = RoundedCornerShape(12.dp),
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(48.dp)
                            ) {
                                Text(
                                    text = if (currentQuizIndex < generatedQuestions.size - 1) "Next Question" else "Finish & View Analysis",
                                    color = Slate950,
                                    fontWeight = FontWeight.Bold
                                )
                            }
                        }
                    }
                }
            }
        } else {
            // Quiz Summary & Telemetry Insights
            val accuracy = ((correctQuizScore.toFloat() / generatedQuestions.size) * 100).toInt()

            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding)
                    .padding(horizontal = 16.dp),
                contentPadding = PaddingValues(top = 16.dp, bottom = 40.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                item {
                    Card(
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = Slate900),
                        border = BorderStroke(1.dp, Slate800),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(
                            modifier = Modifier.padding(20.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(
                                text = "QUIZ PERFORMANCE SCORE",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                letterSpacing = 1.sp,
                                color = CyanPrimary
                            )
                            Spacer(modifier = Modifier.height(8.dp))
                            Text(
                                text = "$accuracy%",
                                fontSize = 36.sp,
                                fontWeight = FontWeight.Black,
                                color = if (accuracy >= 70) EmeraldSuccess else CyanPrimary
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Text(
                                text = "$correctQuizScore of ${generatedQuestions.size} Questions Solved Correctly",
                                fontSize = 13.sp,
                                color = Color.White
                            )
                        }
                    }
                }

                // AI Weak Topic Breakdown
                item {
                    Card(
                        shape = RoundedCornerShape(14.dp),
                        colors = CardDefaults.cardColors(containerColor = Slate900),
                        border = BorderStroke(1.dp, Slate800),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(modifier = Modifier.padding(16.dp)) {
                            Text(
                                text = "Concept Breakdown",
                                fontSize = 14.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White
                            )
                            Spacer(modifier = Modifier.height(8.dp))
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Box(modifier = Modifier.size(8.dp).clip(CircleShape).background(EmeraldSuccess))
                                Spacer(modifier = Modifier.width(6.dp))
                                Text("Strong: Heating Effect, Temperature Coefficient", fontSize = 12.sp, color = EmeraldSuccess)
                            }
                            Spacer(modifier = Modifier.height(4.dp))
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Box(modifier = Modifier.size(8.dp).clip(CircleShape).background(RoseError))
                                Spacer(modifier = Modifier.width(6.dp))
                                Text("Needs Focus: Kirchhoff's Voltage Law", fontSize = 12.sp, color = RoseError)
                            }
                        }
                    }
                }

                // Schedule revision button
                item {
                    Button(
                        onClick = {
                            viewModel.addRevisionToSchedule(chapter?.subjectId ?: "PHYSICS", "Kirchhoff's Laws")
                            onNavigateBack()
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = CyanPrimary),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(48.dp)
                    ) {
                        Text("Add Kirchhoff Revision to Schedule", color = Slate950, fontWeight = FontWeight.Bold)
                    }
                }

                item {
                    OutlinedButton(
                        onClick = onNavigateBack,
                        colors = ButtonDefaults.outlinedButtonColors(contentColor = Color.White),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Text("Back to Chapter")
                    }
                }
            }
        }
    }
}
